version: "2.1"

volumes:
    db:
    elasticdata:
    redis-data:

services:

  php:
    image: trydirect/sylius:1.7.3
    build: dockerfiles/php
    restart: always
    container_name: php
    links:
      - db
    working_dir: /var/www/html
    env_file:
      - .env

  node:
    image: node:8.15
    container_name: node
    environment:
      YARN_CACHE_FOLDER: '/home/node/.yarn-cache'
    user: node
    volumes:
      - ./sylius:/var/www/html
      - ./sylius/.cache/yarn:/home/node/.yarn-cache
    working_dir: /var/www/html

  elasticsearch:
    image: elasticsearch:5.4.3
    restart: always
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - php
    depends_on:
      - php
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  kibana:
      image: kibana:5.4.3
      restart: always
      container_name: kibana
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      env_file:
        - .env
      volumes:
        - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
      image: optimum/logstash-symfony-5.4.0
      environment:
        LS_JAVA_OPTS: "-Xms1g -Xmx4g"
      container_name: logstash
      restart: always
      ports:
        - "5044:5044"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
      volumes:
        - ./configs/logstash/filebeat.conf:/usr/share/logstash/pipeline/filebeat.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.7.1
    restart: always
    container_name: filebeat
    user: 0:0
    env_file:
      - .env
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash

  redis:
      image: redis:latest
      restart: always
      container_name: redis
      env_file:
        - .env
      volumes:
        - redis-data:/data

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      .env
    volumes:
      - db:/var/lib/mysql

# entry point
  nginx:
    image: ${REGISTRY}trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - kibana
    volumes:
      - ./configs/nginx/conf.d/.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./configs/certs/ssl:/etc/nginx/ssl
      - ./configs/certs/letsencrypt:/etc/letsencrypt
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/supervisord:/etc/supervisor/conf.d/
      - ./configs/cron/nginx:/var/spool/cron/crontabs
      - ./sylius:/var/www/html
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  # basic data bus for interaction between servers
  mq:
    container_name: mq
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    ports:
      # note! from others containers need connect to 5672 port, not 2172
      # 2172 using for debug
      - "2172:5672"
      - "5672"
      - "21072:15672"
